### PR TITLE
Validate discipline incident codes, improve local data

### PR DESCRIPTION
**Pull request by kevinrobinson**
# Who is this PR for?
developers, designers

# What problem does this PR fix?
Document expected values for incident codes, for validate and for building features around this.

# What does this PR do?
Adds a validation which adds in codes that we see, and also improves the local demo data to use real codes and locations.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@edavidsonsawyer This might help a bit with https://github.com/studentinsights/studentinsights/pull/1502 too.

**Comment by edavidsonsawyer** [comment]
@kevinrobinson this is great! Where did these come from? Is it a Somerville specific list?

**Comment by kevinrobinson** [comment]
@edavidsonsawyer Yep, these is the aggregate of `DisciplineIncident.all.map(&:incident_code).uniq.sort` across all data we import in Somerville.  I assume it's a combination of how Somerville defines this, how Aspen supports this, and what DESE requires for reporting, but getting into more details there is probably a conversation for email.  This isn't trying to make realistic distributions or anything, just to make the codes quasi-realistic rather than the placeholder "A", "B", "C" they were before.

**Comment by kevinrobinson** [comment]
Pushed another commit that updates all the specs to now use valid data, and removed the `FakeDisciplineIncident` class since it and the factory were doing the same thing.

**Pull request merged**
