### PR TITLE
Add codemod for converting to JSX

### PR DESCRIPTION
**Pull request by kevinrobinson**
Use https://github.com/cpojer/js-codemod and a tiny fork at https://github.com/kevinrobinson/react-codemod to run codemods and convert things to JSX and use const over var where possible.

@alexsoble Check out the diff, we could use this to convert things all at once.  It just needs to get smarter about renaming these files to JSX (and we could remove the "imports" for `dom` and `createEl` too.  Separately, we could do something similar for converting `window.shared` to ES6 imports as well.

More background if you're curious: https://medium.com/@cpojer/effective-javascript-codemods-5a6686bb46fb#.7dkmg6l3b

### CODE REVIEW

**Comment by alexsoble** [comment]
Woaaaaaaah. Very cool. Excited to play with this when I'm in front of a
computer.
On Fri, Mar 10, 2017 at 5:50 PM Kevin Robinson <notifications@github.com>
wrote:

Use https://github.com/cpojer/js-codemod and a tiny fork at
https://github.com/kevinrobinson/react-codemod to run codemods and convert
things to JSX and use const over var where possible.

@alexsoble <https://github.com/alexsoble> Check out the diff, we could use
this to convert things all at once. It just needs to get smarter about
renaming these files to JSX (and we could remove the "imports" for dom and
createEl too. Separately, we could do something similar for converting
window.shared to ES6 imports as well.

More background if you're curious:
https://medium.com/@cpojer/effective-javascript-codemods-5a6686bb46fb#.7dkmg6l3b
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/studentinsights/studentinsights/pull/879
Commit Summary

   - Add codemod for converting to JSX

File Changes

   - *R* app/assets/javascripts/student_profile/note_card.jsx
   <https://github.com/studentinsights/studentinsights/pull/879/files#diff-0>
   (131)
   - *A* scripts/codemods/to_jsx.sh
   <https://github.com/studentinsights/studentinsights/pull/879/files#diff-1>
   (42)

Patch Links:

   - https://github.com/studentinsights/studentinsights/pull/879.patch
   - https://github.com/studentinsights/studentinsights/pull/879.diff

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/studentinsights/studentinsights/pull/879>, or mute the
thread

**Comment by kevinrobinson** [comment]
👍 I'm away for much of this week, but will move forward with this next week then.  Thanks yall!

**Comment by alexsoble** [comment]
Woohoo, this codemod is super, super useful! Thanks for finding @kevinrobinson! 

aa58b8fb66f05f8304e959cada30b57fe0c2d1c5: did the little file renaming bit at the end

f0619feab98188a39e888858b428a14e4dc2a722: target only the dirs with JS that we want to turn into JSX; loop through them and run the codemod on all JS files

We've merged in some new JS since this branch was opened, I'm going to rebase it onto master so that we can run the codemod on all the most up-to-date JS.

**Comment by alexsoble** [comment]
4e512ec64ca3edf78928ad0c66bb9276486272db: results of running the codemod  :D 

This looks really good to me. `bundle exec teaspoon` passes, and the site looks in good working order when inspected manually post-codemod. 

Kevin, I see you wrote `TODO ES6 class transform`, but my suggestion is that we merge the JSX transform in first and then the ES6 class transform later.

 Why? Because the ES6 class transform will require a bunch of changes to the JS specs. Let's handle that next and merge this in the spirit of "merge early & often", since the JSX transform didn't break the specs at all. 

My suggestion for merging:

1. Merge branch in and push live on Monday (merging in a codemod on a Friday seems like an invitation for trouble).
2. Once we merge this in, all future work on the React files should be in JSX only -- is this good with all active contributors? cc: @kevinrobinson @jhilde @pauledwardmitchell 
3. Beef up the codemod to handle ES6 class transforms and repeat

**Comment by jhilde** [comment]
@alexsoble @kevinrobinson Could we push my code first (#886) so the transforms happen on it? :-)

**Comment by jhilde** [comment]
But yes, psyched about the switch to JSX. Perhaps it's the lots of coding around XML in me.

**Comment by kevinrobinson** [comment]
@alexsoble just saw this, it all sounds awesome and thanks for helping out with this!  👍  And agree completely on the ES6 transform too.

**Comment by kevinrobinson** [comment]
@jhilde The merge order should be cool either way, if this lands first we can point this script at the code in your branch to transform it too. :)

**Comment by alexsoble** [comment]
🚢 ing

@jhilde, to use this on your own code you'll run this in the command line from the root dir of the project:

```
scripts/codemods/to_jsx.sh
```

**Comment by alexsoble** [comment]
Looks good in prod.  :0)

**Comment by pauledwardmitchell** [comment]
NICE WORK PEOPLE. @alexsoble @kevinrobinson @jhilde YALL ARE THE BEST.

**Comment by kevinrobinson** [comment]
🚢 🎉

**Pull request merged**
