### PR TITLE
Patch: Remove duplicate test code for #select edge case on feature/authorization-simple

### PR DESCRIPTION
**Pull request by alexsoble**
# What does this PR do?

+ Removes duplicate test code for `#select` edge case

### CODE REVIEW

**Comment by alexsoble** [comment]
Note to self: you can finish up this patch, you don't need to test this under a lot of contexts because this is an edge case you're testing, also it doesn't apply to district admins because they bail out early in the authorization tree.

**Comment by alexsoble** [comment]
Also don't call JSON in this test.

**Comment by kevinrobinson** [comment]
@alexsoble I pushed a commit fixing this up here: https://github.com/studentinsights/studentinsights/pull/1274/commits/20f54407c5ae3cc95377d99dc1250bac0b697710

**Comment by alexsoble** [comment]
@kevinrobinson Oh great. Yep, just saw it. So it looks like this spec was being difficult because there was a real bug in the feature side code. Exactly what we want our specs to do!

**Pull request closed without merging**
