### PR TITLE
Discipline Dashboard release

### PR DESCRIPTION
**Pull request by edavidsonsawyer**
# Who is this PR for?
Educators

# What problem does this PR fix?
The discipline dashboard is available in production, but there are no live links to the feature. 

# What does this PR do?
Adds links to the discipline dashboard alongside the tardies/absences dashboards

# Screenshot (if adding a client-side feature)
admin_disc_links
teacher_disc_links

# Checklists
*Which features or pages does this PR touch?*
+ [x] Home page

*Does this PR use tests to help verify we can deploy these changes quickly and confidently?*
+ [x] Included specs for changes
+ [x] Manual testing made more sense here

### CODE REVIEW

**Comment by edavidsonsawyer** [comment]
@kevinrobinson I have this ready to go but we probably want to hold off on this request until we have a solution for the SHS loading time. I'm working on that today.

**Comment by kevinrobinson** [comment]
@edavidsonsawyer Awesome!  This looks good, and can we remove the experimental banner too when this is ready to go out?  The other wrinkle here is that some users have additional links on the navbar - you can sign in as the `jodi` or `harry` user to see this.  I think it will fit with a 1024px wide screen, but can you confirm?

re: SHS loading, I think the issue is the n+1 where it queries for all students, then for each one queries for discipline incidents.  The absences page batches these queries up and might be a model to check out: https://github.com/studentinsights/studentinsights/blob/master/app/lib/dashboard_queries.rb#L8.  If there are ways to make smaller changes that'd be great to try, but just using the same approach as the absences page is fine too, which might be easier without profiling.

**Comment by edavidsonsawyer** [comment]
@kevinrobinson thanks for flagging the users with extra links. I tested with both of them at a bunch of resolutions and everything seems to fit. One note is that I don't think the Jodi user is supposed to have access to the dashboards (she doesn't now). Is that not correct?

**Comment by kevinrobinson** [comment]
hi eric, awesome!  yeah sorry I think I mixed up the names then

**Comment by edavidsonsawyer** [comment]
@kevinrobinson okay, the banner is out, so this should be ready when we want to merge it.

**Pull request merged**
