### PR TITLE
change recorded_at to discontinued_at for discontinuedservice model

### PR DESCRIPTION
**Pull request by Jngai**
#839 
@alexsoble Basically I made a migration to change the name, then change `recorded_at` to `discontinued_at` wherever I can find for `discontinuedservice` model. The tests went down to red. I made each test green again. Its good for a review.

### CODE REVIEW

**Comment by alexsoble** [comment]
Wow, fantastic @Jngai! Thanks for the contribution, I'll review right now, that red-to-green path you described sounds perfect! :)

**Comment by alexsoble** [comment]
Also once we merge this will fix #839!

**Comment by alexsoble** [comment]
This is in production @Jngai!

**Comment by Jngai** [comment]
Thanks @alexsoble ! I am looking at other issues and if I have something I will make a pr for another issue.

**Pull request merged**
