### PR TITLE
Draft helptext for Restricted Notes

### PR DESCRIPTION
**Pull request by alexsoble**
note helptext ars

### CODE REVIEW

**Comment by awalker4** [comment]
Your first restricted example is also in the first list. Not sure if that was intentional!

**Comment by alexsoble** [comment]
@awalker4 — Good catch, thank you! I think I fixed in the rebase. Will double check!

**Comment by alexsoble** [comment]
screen shot 2016-06-05 at 2 33 21 am

**Comment by alexsoble** [comment]
Fixed during rebase, thanks for catching though @awalker4!

**Pull request merged**
