### PR TITLE
Bar charts for behavior data

### LINKED ISSUE #343: Bar charts instead of line charts for absences, tardies, discipline incidents
Visited the 6th grade teacher team at the Healey school this morning to show them the latest iteration of Student Insights and get their feedback.

The teacher team found the peaks and valleys in the attendance/tardies charts confusing. It looked to them like the students were making progress at the end of each year when the line fell, because it wasn't obvious that the line represented cumulative values over each school year:

absences line chart

The teacher team and Jill had an alternative suggestion: using bar charts. The bar could show the number of absences/tardies/discipline incidents as the height, with the month on the X-axis. This would allow educators to see change in absences or tardies over a single school year while making the data easier to read.

### PR DESCRIPTION
**Pull request by erose**
Moves the charts for behavior & attendance over to bar charts ("column" charts in Highcharts) from line charts. Mouseover on a bar for some month will bring up a list of the events that happened in that month.

Introduces a new React component, `profile_bar_chart.js`.

screen shot 2016-04-22 at 2 59 33 pm

Fixes #343 

Would love a code review and/or UI feedback!

### CODE REVIEW

**Comment by erose** [comment]
**Here's an alternate look**, which I have on another branch.

screen shot 2016-04-22 at 5 02 41 pm

Let me know if you prefer this one.

**Comment by alexsoble** [comment]
Thanks for tackling this, @erose!

Here is my feedback:

__CODE__

+ It would be good to write a spec for `profile_bar_chart.js`. 

  + In general, any feature that adds significant complexity should get a spec. We've had two bugs that caused data to be shown incorrectly because of front-end bugs/mixups in the past couple of weeks: #363 and #415. Spec coverage for all our front-end features will help.

  + Eli, are you familiar with JS specs? If not, this is something we could pair on together at Code for Boston on Tuesday. 

__UI DETAILS__

+ Noticed a couple of small possible improvements as I was playing around, offering as suggestions:

  + "Discipline Incidents, last 48 months" — The chart titles made me pause for a second to do mental math. Divide by 48 by 12: "oh, okay, last four years." Small thing, but easier for a viewer to mentally process number of years than number of months.

  + Date formatting in the tooltips could match the Full Case History formatting, i.e. "April 24th, 2016" instead of "04-24-2016".

__MILESTONE__

This is a great pull request because (among other reasons!) it resolves our last open issue in the Profile Page V2 milestone. That is a big deal: thank you for pushing this across the finish line, Eli! 

🎉  🎉  🎉 

I already pushed to staging and demo in the process of doing manual QA. I'll merge now and push to production, then I'd say our next order of business should be the spec.

**Comment by erose** [comment]
Thanks for merging & QA'ing, Alex! Didn't even know this was the last one on the milestone. I agree with you on the UI stuff -- my fear was that "last n years" implies we cover the whole last n calendar years, start-to-finish, but that's just my hangup, no idea if it bothers our users or not.

Implemented and merged the UI fixes in #420.

Yeah let's pair on doing the spec, that sounds fun & morally improving!

**Comment by alexsoble** [comment]
@erose Indeed, like vegetables for your code!

**Pull request merged**
