### PR TITLE
formatGradeNumber function 

### PR DESCRIPTION
**Pull request by BWieber**
Hi Kevin, 

@erose and I worked on this, and got it up and running :) Unfortunately the students in the demo file are only in the 5th grade, but as you can see it is working for that use-case. Take a look! 

formatstudentgrade

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@BWieber :facepunch: This looks good, thanks!

To merge this, you'll have to do a similar merge as I described in https://github.com/studentinsights/studentinsights/pull/108#issuecomment-188304087, since there are additional commits on the other branches.  My recommendation would be to finish off https://github.com/studentinsights/studentinsights/pull/108 first, then move to this one.  And in general, I find that when making changes like this that are so closely related and changing together in the span of a few hours, it's often easier to work on one branch rather than a separate ones.

This does the trick for our limited use case as you mention, so I'd say after merging in the other commits, let's :ship: this.  FWIW, [numeral.js](http://numeraljs.com/) is a library that handles these kinds of string conversions and is usually a better bet when you want something more general.

**Comment by BWieber** [comment]
Hey Kevin! 

I checked out both branches and I can identify any merge conflicts. I switched to both the `risk_box` branch and the `format_student_grade` branch, and both of them were already up to date with master. 

Let me know if there is another step I am missing, otherwise, all is up to date!

**Comment by kevinrobinson** [comment]
@BWieber cool, let's talk it out manana. :)

**Comment by kevinrobinson** [comment]
@BWieber let's close this and move the work to https://github.com/studentinsights/studentinsights/pull/108 like we just talked about!

**Comment by BWieber** [comment]
Closed - Branched was merged with `risk_box`

**Pull request closed without merging**
