### PR TITLE
Continue with service

### PR DESCRIPTION
**Pull request by Jngai**
Checking to see if estimated_end_date is valid with momentjs plus write a rake task to backfill existing services. #1101

### CODE REVIEW

**Comment by Jngai** [comment]
@alexsoble I resolved the conflicts. Please review and don't forget to revert the other pr with the bulk of my work. This is the supplement to that other pr which I can't open again.

**Comment by Jngai** [comment]
@alexsoble Looks like I don't have write access. The rake task is working and I added to deploy.sh. I will make a pr to comment those out once they run successfully.

**Comment by alexsoble** [comment]
Ok, thanks @Jngai! I will test this out (including the migration you wrote) on the demo site and then if all looks 👍  deploy to the production site!

**Comment by Jngai** [comment]
@alexsoble Great Thanks!

**Comment by alexsoble** [comment]
Looks good in the demo site @Jngai. However I'm a bit unclear on which PRs I need to merge in in which order. Is merging in this PR and deploying not enough to land the feature?

**Comment by Jngai** [comment]
@alexsoble I reverted your reverted commit on my old pr so this pr has everything.

**Comment by Jngai** [comment]
I am glad it looks good on the demo site.

**Comment by Jngai** [comment]
btw @alexsoble I am using the _first_ discontinued_at for the new field.

**Comment by alexsoble** [comment]
@Jngai Makes sense, I think that's a good assumption!

**Comment by alexsoble** [comment]
Looks good in production, congrats @Jngai!

🎉 🎉 🎉

**Comment by Jngai** [comment]
@alexsoble Awesome! I will check it out in demo site later.

**Pull request merged**
