### PR TITLE
Bar chart sparklines

### PR DESCRIPTION
**Pull request by erose**
Resolves https://github.com/studentinsights/studentinsights/issues/593.

First pass. Design feedback wanted!

screen shot 2016-06-29 at 4 52 45 pm
screen shot 2016-06-29 at 4 52 51 pm

### CODE REVIEW

**Comment by awalker4** [comment]
My eyes keep expecting those horizontal lines to be y=0 and then I get pretty confused when it looks like everything is negative. How would it look with a solid line on the bottom so those rectangles are a bit more grounded?

**Comment by erose** [comment]
@awalker4: I agree, here's how it looks now.
screen shot 2016-06-30 at 1 45 43 pm

**Comment by alexsoble** [comment]
@erose What are the dividing units on the X-axis?

**Comment by erose** [comment]
@alexsoble: The two big vertical lines? Those are starts of school years. (August 15th 2015, August 15th 2014).

I don't think that's clear. Should we try to indicate it better, or just lose them? (since this is just a sparkline not a full graph).

**Comment by kevinrobinson** [comment]
@erose Nice!  This seems like a great improvement to me, and the suggestions of clarifying the time sound 👍 too.

**Comment by alexsoble** [comment]
@erose I think some way to indicate that is important. Maybe a mini-legend at the bottom?

**Comment by alexsoble** [comment]
Hey @erose. I think this is excellent work, I apologize if my suggestions/comments about the X-axis have slowed us down from merging it. Why don't we merge it in now (solid improvement from the line graphs) and we can think more about the X-axis labeling as a next step?

**Comment by erose** [comment]
@alexsoble: Dude, that's not on you! I agree, (merged), I'll think about it more + iterate more when I see it in production.

**Comment by alexsoble** [comment]
Pushed to production! These look nice!

**Pull request merged**
