### PR TITLE
Newsfeed

### PR DESCRIPTION
**Pull request by erose**
Bare-bones implementation of a newsfeed on profile v2, which displays events sorted chronologically, where an "event" is an:
  * absence
  * tardy
  * Math or ELA score on the MCAS or STAR test

Each event consists of:
  * its date of occurrence
  * a short description string with the student's name

e.g. "Monday, February 12th, 2016: Aladdin was tardy" or "Tuesday, April 15th, 2016: Aladdin scored a 37% on the Math section of the MCAS."

screen shot 2016-02-23 at 3 48 00 pm

### CODE REVIEW

**Comment by erose** [comment]
Oops, this pull request contains the changes from `refactoring_profile_js` as well!

**Comment by kevinrobinson** [comment]
@erose wow, nice work this looks great!

No worries about the other changes, you can rebase and squash those other commits out, or we can just merge https://github.com/studentinsights/studentinsights/pull/104 shortly. :)  Let's get this merged tonight too. :smile:

**Comment by kevinrobinson** [comment]
Also, might be good to add a smoke test in Jasmine for this component too, I can show you how to get started with that if you want, or https://github.com/studentinsights/studentinsights/blob/master/spec/javascripts/student_profile_v2/take_notes_spec.js might be a good model.

**Comment by kevinrobinson** [comment]
Awesome, this looks great, thanks @erose! :grinning:

**Pull request merged**
