### PR TITLE
Header Contact Info

### PR DESCRIPTION
**Pull request by gabivoicu**
Solves [Issue 1087](https://github.com/studentinsights/studentinsights/issues/1087)

add new icon to student profile header; add new icon file; make icon open modal on click

# ToDo before merge

+ [x] UI: we decided that the smaller modal just needs one (close) button instead of two
+ [x] UI: maybe shrink the icon a little?
+ [x] linting: went over `npm lint` together
+ [x] tests: integration test is broken, might be because element we're clicking on isn't the element with `onClick` defined

# Screenshots
screen shot 2017-10-24 at 6 28 01 pm
screen shot 2017-10-24 at 6 28 05 pm

### CODE REVIEW

**Comment by gabivoicu** [comment]
@alexsoble Couple questions/thoughts about this issue so far:
- the icon downloaded from the Noun Project has some copyright text at the bottom that we could get rid of if we paid for it, is that an option? (The paid icon also has the option of downloading in another color, it would look a lot better in the blue color we use on that line). Alternatively, I've used Font Awesome before and had good results with it, as a free alternative that's more customizable and we could use for many other icons down the road. What are your thoughts on this?
- as a first pass, I used the `HelpBubble` for the modal; I considered using that (and renaming the original class so we can reuse it in multiple places), but I think a full page modal is too much for the contact info. I will try the `RiskBubble` as well, and consider writing a new class entirely. I might come back with questions once I have something working for feedback on the UI
- timeline-wise, I am still predicting to be done with this by the end of the weekend, early next week

**Comment by alexsoble** [comment]
Hey @gabivoicu!

+ Buying a royalty-free license for a single Noun Project icon costs around $2, so I'd say go ahead and buy the $2 license and add it to your invoice for this chunk of work. Including the entire font-awesome library in the project to add just one icon seems like it would be overkill. 
+ Re: `HelpBubble` — sounds like a plan!

**Comment by gabivoicu** [comment]
@alexsoble Sounds good, I will do that!

**Comment by gabivoicu** [comment]
hey @alex, some more questions:
- re: the noun project: where exactly can one buy a single icon? I've looked around the website extensively and all I can find is subscription-based purchases ($39.99/year regular, or $19.99 for educators)
- is there a spot I can look at to customize the size of `HelpBubble`? from what I can see in `/help_bubble.jsx` is uses the `ReactModal` element but I've had no luck figuring out how to customize it (in the codebase or google). I'm also considering keeping the modal the same size as everywhere else for consistency, but it might be overkill 🤔
- is this the best way to ask all of these questions, or would email/something else be better? I worry it adds a lot of noise to the PR

**Comment by alexsoble** [comment]
Hey @gabivoicu!

* If you send me the link to the Noun Project Icon you like I can buy it for the project.
* Looking at https://github.com/reactjs/react-modal — I see there' a `style` prop we can pass to the Modal component, that could be a good way to customize it:

```
<Modal
  isOpen={bool}
  onAfterOpen={afterOpenFn}
  onRequestClose={requestCloseFn}
  closeTimeoutMS={n}
  style={customStyle}
  contentLabel="Modal"
>
  <h1>Modal Content</h1>
  <p>Etc.</p>
</Modal>
```

* Asking questions in this thread is just fine! I think it's generally better than email because it's public and anyone from the team can jump in to answer if they have a good idea

**Comment by gabivoicu** [comment]
@alexsoble:
- I will pick an icon and send you the link; I'm going to try and find a new one, I think even in a different color the one I'm using right now feels a bit too heavy, I will try to find one with more white space in it for a lighter feel
- thank your for the link & direction, I was looking at that repo and couldn't tell if it was what we were using or not (they use the name `Modal` in there and we use `ReactModal` and I was confused about them being the exact same thing)
- sounds good, I'll keep asking here
Thank you!

**Comment by gabivoicu** [comment]
An update on timeline: I had some things come up the past couple of days, and I am looking to be code complete by Friday.

**Comment by gabivoicu** [comment]
@alexsoble Update on the icon: I found the spot where I can buy the icon for $2, however that only gets me the black icon, to get it in blue it appears is only possible with the Pro version. Thoughts? [Here](https://thenounproject.com/search/?q=contacts%20book&i=780817) is the new one I want to use, ideally in the `#51A7F9`.

**Comment by alexsoble** [comment]
And we QA'ed on a IE 11 VM! Looks ✅ !

**Comment by kevinrobinson** [comment]
@gabivoicu I submitted https://github.com/gabivoicu/studentinsights/pull/1, which is a pull request into your branch here that you can merge into your work here to resolve the merge conflicts introduced in https://github.com/studentinsights/studentinsights/pull/1182.

There's a tiny change https://github.com/gabivoicu/studentinsights/pull/1/files#diff-81e113f3a1d5f9412ddecd36047fa42eR133 and in the specs: https://github.com/gabivoicu/studentinsights/pull/1/files#diff-b9cff4fddcc6d549df41c051ed4e6995R33.

**Comment by gabivoicu** [comment]
@kevinrobinson Sounds good, thank you Kevin, I will get that merged in. This might actually help get those tests working, I'll check soon.

**Comment by kevinrobinson** [comment]
@gabivoicu I tried to leave everything as it was and just resolve the merge conflict, so it won't fix the tests :)

It looks like the modal either isn't popping up in the test (maybe because simulating the click event is working) or that the test code is looking for the modal in the wrong place on the page.  You can try adding in a bunch of `console.log` statements to see what's going on.  The way you run tests will be different now too, so let me know if you have any questions, hopefully this is minimally disruptive and helps makes your development experience better!

**Comment by gabivoicu** [comment]
Hope springs eternal, @kevinrobinson. These tests have been causing me grief, something is definitely happening with the modal, I will continue investigating. From the print statements I added everywhere it seems the click is happening, but the modal still seems to be empty somehow.

I'll try running the tests the new way and get back to you.

**Comment by gabivoicu** [comment]
@alexsoble Tests seem to be failing on Travis still, not sure why yet, will look into this later tonight or tomorrow and ping you when it's ready for a review/

**Comment by Jngai** [comment]
@gabivoicu is this line `1 Memorial Dr, Cambridge, MA 02142`. If the expectation of this existing no longer applies because you redesigned the view then you need to remove this line from the spec and the fixture.

**Comment by Jngai** [comment]
sorry @gabivoicu I wasn't following the conversation.  It could be something else according to comments above. I can help too next week.

**Comment by gabivoicu** [comment]
@Jngai No problem, thank you for trying to help Judy! I'll ping you if I can't figure it out over the weekend, thanks!

**Comment by gabivoicu** [comment]
@Jngai You were absolutely correct, it was because I had manage to reintroduce the old test through some weird stash/merge issue 😁 So glad I looked at it today with fresh eyes and didn't try to fix it yesterday, it was so fast to solve.

@alexsoble The build is PASSING and this PR is ready for review 🎉 So excited, please let me know what I can improve in it 😁

**Comment by Jngai** [comment]
Great @gabivoicu I remember you asked if you can remove the address at a meeting so I wasn't expecting the address to still be in the pr. Glad you fixed it.

**Comment by Jngai** [comment]
@gabivoicu `1 Memorial Dr, Cambridge, MA 02142` is still in the fixture. If you don't need that then please remove that too.

**Comment by alexsoble** [comment]
@gabivoicu This looks good to me, merging and deploying now! ⚙️  ⚙️  ⚙️

**Comment by alexsoble** [comment]
@gabivoicu Looks good in prod! You can also see it live on the demo site at https://somerville-teacher-tool-demo.herokuapp.com/! 🎉

**Comment by gabivoicu** [comment]
🎉🎉🎉
I checked it out, looks great, yay :D

**Pull request merged**
