### PR TITLE
Student profile sped

### PR DESCRIPTION
**Pull request by pauledwardmitchell**
Hey @alexsoble!

Here is the SpEd Level feature for the Student Profile page.

image

image

Happy to refactor sans JSX.

### CODE REVIEW

**Comment by alexsoble** [comment]
Talking with @pauledwardmitchell now, we agreed it might make more sense to write, i.e. "6-14 hours of services" under SpEd services instead of the "Level of Need", which is a little more cryptic/opaque.

**Comment by pauledwardmitchell** [comment]
@alexsoble - let me know what you think!

image

**Comment by pauledwardmitchell** [comment]
Hey @kevinrobinson - 

This PR renames student_profile_page.js to student_profile_page.js.jsx ... @alexsoble and I were talking just now and I wondered if this change would interfere with codemod.  Let me know!  I'm happy to refactor sans JSX.

**Comment by kevinrobinson** [comment]
@pauledwardmitchell Cool!  Thanks for the ping.  My suggestion would be that within a single file we always keep consistent about whether we use `dom.div` and `createEl` or whether we use JSX.  So my suggestion for this PR would be to either stick with the current style, or to convert the entire file to JSX, rather than using both approaches within a single file.

If you'd like to convert, you could do it all by hand, or try grabbing https://github.com/studentinsights/studentinsights/pull/879 and running that on this file.  Alternately, I'm happy to do the conversion work as part of that PR, so we can decouple that from your great work to ship new features here.

**Comment by pauledwardmitchell** [comment]
This makes sense, @kevinrobinson - I will refactor without JSX to keep consistent.

**Comment by pauledwardmitchell** [comment]
JSX-less! Should be good to go, @alexsoble .

**Comment by kevinrobinson** [comment]
No prob @pauledwardmitchell!  👍

**Comment by alexsoble** [comment]
@pauledwardmitchell 👍

**Pull request merged**
