### PR TITLE
Sort grades on roster numerically

### PR DESCRIPTION
**Pull request by kevinrobinson**
eg for section 1588:
screen shot 2017-09-20 at 11 09 07 pm

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@jhilde seem good?

**Comment by jhilde** [comment]
Yes thanks @kevinrobinson.

**Comment by jhilde** [comment]
Thanks for pushing @alexsoble. Wasn't sure who was gonna push. ;-)

**Comment by kevinrobinson** [comment]
👍 I'm just slow thanks y'all!  Please feel free to just grab anything like this that's ready but not shipped and ship it out on your own if that happens again too :)

**Pull request merged**
