### PR TITLE
Drive down linter errors

### PR DESCRIPTION
**Pull request by alexsoble**
Woooohooo fixing eslint stuff!

### CODE REVIEW

**Comment by alexsoble** [comment]
Down from 200+ errors to . . . 74!

**Comment by alexsoble** [comment]
66!

**Comment by kevinrobinson** [comment]
@alexsoble hehe awesome!
image

**Comment by alexsoble** [comment]
@kevinrobinson lol

**Comment by alexsoble** [comment]
39

**Comment by alexsoble** [comment]
(i did all the ones that required zero critical thinking)

**Comment by alexsoble** [comment]
diff is big... tests are green...
linter errors dipping.
everything looks good on dev,
which means that this is 🚢 ing

**Pull request merged**
