### PR TITLE
Un-revert: Store user login attempts with authtrail

### PR DESCRIPTION
**Pull request by alexsoble**
Reverts studentinsights/studentinsights#1904.

Re-attempting to deploy authtrail. #1905 means that the app shouldn't blow up on first boot. 

I'm going to rebase this on top of #1907 so that Travis can tell us whether it will boot successfully before we merge and deploy.

### CODE REVIEW

**Comment by alexsoble** [comment]
No rebasing required: `eager_load` is set to `true` on this branch so I'll watch Travis.

**Comment by alexsoble** [comment]
Tests pass! 🚢

**Comment by alexsoble** [comment]
Manually verified by attempting to log in a few times and checking the results in the `LoginActivities` table. Looks good! 👍🌈✨

**Comment by kevinrobinson** [comment]
@alexsoble FYI the masquerading PR (https://github.com/studentinsights/studentinsights/pull/1793) doesn't show up in the `LoginActivity` table, which I think is good and what we'd want.

**Pull request merged**
