### PR TITLE
Display grade level on x-axis of charts.

### LINKED ISSUE #345: Show grades in addition to school years on profile chart X-axis
Visited the 6th grade teacher team at the Healey school this morning to show them the latest iteration of Student Insights and get their feedback.

They mentioned that instead of only showing school years on the X-axis of charts, it would be more intuitive for them if the charts included grade level information as well: "Grade 5, 2012-2013".

### PR DESCRIPTION
**Pull request by erose**
Fixes #345.

I don't think this is ready to be merged yet; I'm putting it here to make public the stuff I've done on it so far.

screen shot 2016-04-25 at 5 19 14 pm

This is only implemented in line charts right now. Issues I want to resolve:

  - [x] Correctness. Right now we assume that every student started at grade 1 and advanced one grade each year. Seems like a bad assumption. Where would we get the data to do this right, i.e. which grade they've been in each year?
  - [x] Code quality. `getPositionsForYearStarts` in `profile_chart.js` is very similar to `getPositionsForYearStarts` in `profile_bar_chart.js`.
  - [ ] Design. I was hemming and hawing on how to represent a school year. Here I did the easiest thing, which was to call Jan 1. the middle of the school year, and put the grade info below it. But it might be confusing. Some different options I can think of are:
    * creating a visual interval with tick marks at the beginning and end.
    * creating a tick mark at the start of each school year.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@erose One quick design thought: the school year is naturally aligned to start in September, not the calendar year, so that might be a more natural label.

**Comment by erose** [comment]
@alexsoble Do you know where I can get the who-was-in-which-grade-which-year data?

**Comment by erose** [comment]
Looks like this now:
screen shot 2016-05-07 at 4 35 59 pm

**Comment by erose** [comment]
For my own reference: adding custom Jasmine tests works like this:

```
  beforeEach(function(){
    jasmine.addMatchers({
      customMatcher: function(actual, expected){
        result = {};

        ... <do stuff> ...
        result.message = result.pass ?
          "Expected + " // Failure if you didn't expect this to pass.
          :
          "Expected"    // Failure message if you did.
        ;
        return result;
      }
    })
  });
```

**Comment by alexsoble** [comment]
@erose We don't have who-was-in-which-grade-which-year data, sadly. Aspen/X2 stores a `grade` column for each student. So it's up to us to walk back through the grade levels, starting with the current year.

**Comment by erose** [comment]
@alexsoble: You're talking about assuming that if a student's in grade 5 this year, they were in grade 4 last year, etc? I was concerned about what if someone got held back or skipped a grade, etc.

But possibly that's not a big deal. I guess I was thinking more about being misleading, rather than not being 100% accurate. Maybe I'll just include some help text explaining that what we're showing is "assumed grade level" or "standard grade level" instead of grade level.

**Comment by alexsoble** [comment]
@erose You make a very important point! Our point person in Somerville for Aspen/X2 is John Breslin, I'll email him about this question and cc you on it.

**Comment by erose** [comment]
@alexsoble @kevinrobinson: Just remembered Kevin said at the last meeting that getting this data was affected by the X2 rollover -- you two should talk.

**Comment by erose** [comment]
Updated to reflect the fact that we now assume the student progressed through grades normally. Now there's the design work left. I think the current thing:

screen shot 2016-05-20 at 2 53 08 pm

is too crowded, but am unsure how to improve it.

**Comment by alexsoble** [comment]
Seems like we could cut the word "started." Is there any way to move the x-axis labels to the center of each pair of tick marks?

**Comment by erose** [comment]
I would like to see the design you had for this, @iamctodd, I know that was posted to Github somewhere but where is it?

**Comment by alexsoble** [comment]
@erose Would you say this one is mergeable or needs-more-work-y? Also looks like it needs a rebase onto master.

**Comment by alexsoble** [comment]
Closing in favor of rebased #760.

**Pull request closed without merging**
