### PR TITLE
Update project priorities

### PR DESCRIPTION
**Pull request by kevinrobinson**
@alexsoble From our conversation last week with Uri.  I also updated the milestones too, but those don't sort so not sure it's super useful.  What do you think makes sense here?  Just trying to visualize the higher-level threads and be able to pick out the issues that matter.

### CODE REVIEW

**Comment by alexsoble** [comment]
@kevinrobinson My thoughts:

+ Nice, thank you for adding this. Good to keep the list up to date.

+ On the X2 roll-over: This will end up being an issue if the data input from X2 changes in an unexpected way. If our import scripts prove really robust, there could be no work here at all. It's kind of a "potential issue", something to keep an eye on more than defined work that needs to be done.

+ I wonder which issues we need to resolve at Healey and West before expanding to East. #450, #451, #452? If we agree with Uri that we should resolve these first, then solidifying Healey / West is one chunk of work and expanding to East and beyond is another.

**Comment by alexsoble** [comment]
@kevinrobinson Another way to organize these:

__MAY / EARLY JUNE__

+ Solidify SST/MTSS at Healey and West
+ Run data import for East and see if we run into issues
+ _Last day of current school year: June 12_

__LATE JUNE / JULY / AUGUST__

+ Import data for all elementary schools
+ Build out whole district classroom teacher rosters and profile for September
+ Keep an eye on X2 roll-over to next school year
+ _August 29: 1st day for Staff Prof. Development_
+ _August 30: Staff Prof. Devel./Paras report to work_
+ _August 31: 1st day for students 1-12 (1/2 day)_

__SEPTEMBER / OCTOBER__

+ Debug, handle feedback, input, and scaling issues from going from 2 schools to 7
+ Concierge PDF data dump of student info through SPED referral process

Source for dates: [2016-17 Calendar](http://www.somerville.k12.ma.us/education/page/download.php?fileinfo=QXBwcm92ZWRfMjAxNi0yMDE3X0NBTEVOREFSXzAyMDQxNi5wZGY6Ojovd3d3L3NjaG9vbHMvc2MvcmVtb3RlL2ltYWdlcy9kb2NtZ3IvMjY4M2ZpbGUxNTE3MC5wZGY=&sectiondetailid=19179)

**Comment by erose** [comment]
Thanks for posting this, it helps me a lot to know where the big-picture stuff is headed. Let's definitely share these at the next meeting.

**Comment by alexsoble** [comment]
Merging in!

**Pull request merged**
