### PR TITLE
WIP - The next section of switching js to es6 import/export 

### PR DESCRIPTION
**Pull request by Jngai**
# Who is this PR for?

Everybody that handles the source code and issue #1180 

# What problem does this PR fix?

Help make all js easier to import and export throughout the app. 

# What does this PR do?
Make js follow es6 rules and constructs. 
# Screenshot (if adding a client-side feature)

# Checklist

+ [ ] Tested latest version in an Internet Explorer virtual machine? *(If the PR adds Javascript.)*
+ [ ] Make sure js files build correct in `yarn start`

### CODE REVIEW

**Comment by alexsoble** [comment]
@Jngai Thanks for all the hard work here Judy! Checking in to ask — is this a good stopping point for us to merge in?

**Comment by Jngai** [comment]
@alexsoble This includes the next section up until student profile. I got a lot of things done but its not there yet because I need to refactor the tests too.

**Comment by Jngai** [comment]
@alexsoble I think we are at a good stopping piont. Can you review my code especially files related to `schooloverview.js`. I am having a little bug going on. I notice some new `schooloverview` related code merged in from master. I also had some merge conflicts. I wonder if that threw this branch off. I am having a bug in the filter from this js file. I need a second eye. Will you check it out?

**Comment by alexsoble** [comment]
@Jngai Yeah. I think we need to do much more careful review on these PRs and check for bugs more carefully, since the last ES6 PR accidentally created a bug in the Student Report PDF: https://github.com/studentinsights/studentinsights/issues/1276#issuecomment-347378944. When I reviewed the last PR in this series I only clicked around the site in a general way, we need to make sure we're systematically QA'ing every feature that has code touched by the PR.

**Comment by alexsoble** [comment]
@Jngai This is a really big list of changes to review effectively. Can you make the review by writing a summary of the changes you made? For example, which files did you refactor to ES6 so that they could be `export`ed? Which pages and features in the UI are affected by this PR?

**Comment by Jngai** [comment]
@alexsoble Yes I saw the bug and I think these conversions are a lot of changes. I am doing this for every single js file. Lets do this slowly and I will spend more time on this to make sure its good.

**Comment by Jngai** [comment]
Hey @alexsoble I think it makes more sense to do this file by file. Please see #1292. Every commit is like a file done. We can do a rigorous QA on each file or two files at a time before we merge them. The list of changes is too big to review effectively. It may take longer but its safer this way. Let me know how you think about this.

**Comment by alexsoble** [comment]
We've moved to a small-PR strategy to get chunks of worked merged in, closing this PR since it changes a very large number of files and it's fallen behind master.

**Pull request closed without merging**
