### PR TITLE
Improving efficiency of db queries for students

### PR DESCRIPTION
**Pull request by edavidsonsawyer**
To help address #1244, this took 1/3 the time to execute the student queries with 500 fake students.

### CODE REVIEW

**Comment by edavidsonsawyer** [comment]
Also removing that errant yarn-error log for #1245

**Comment by alexsoble** [comment]
👍  let's see what kind of improvement this creates in prod!

**Comment by alexsoble** [comment]
Hey @edavidsonsawyer! I pushed this to the live tool and tested it a few times with an in-browser stopwatch. There's definitely an improvement, and it does seem to be in the neighborhood of 1/3 the original time. That puts us from 60 second load times to 20 second load times, which is better but still not in the neighborhood we want to be in.

My suggestion for a next step: @kevinrobinson has been doing some excellent work compressing JSON in #1228. This strategy involves moving from an HTML-rendering path for putting data on the page to a JSON-oriented path where an HTML page loads, the JS runs, and it requests data via a JSON endpoint that can be compressed and help optimize. 

I'm going to work on merging in @kevinrobinson's #1228 (looks like it has a couple of merge conflicts) so that we can take advantage of the compression/optimization he's unblocked for us. 

If you have other suggestions or strategies we should try @edavidsonsawyer please post them! Let's keep working on this until the load time gets pushed down into the neighborhood we want!

**Comment by edavidsonsawyer** [comment]
Thanks, @alexsoble! The stuff @kevinrobinson is doing looks promising. I'll add further suggestions to #1244. In the meantime, would you be able to check on the prod site and see the effect of changing the dates via the slider? I suspect the slowness isn't coming from the render but I want to make sure that's the case.

**Comment by edavidsonsawyer** [comment]
Hey @alexsoble and @kevinrobinson! I'm noticing the school view (which I'd imagine has some of the same problems the dashboard does) takes advantage of a precompute job. Is there any objection to my adding some dashboard specific tasks there?

**Comment by alexsoble** [comment]
@edavidsonsawyer When I move the sliders it takes about five seconds (counting out loud) for the data to update.

**Comment by edavidsonsawyer** [comment]
@alexsoble thanks. There's probably some optimizations I can do in there.

**Comment by alexsoble** [comment]
@edavidsonsawyer Ya, my feeling is let's make sure we've tackled the productive optimizations available to us in the existing code before adding a precompute jobs. Precompute jobs are awesome but sometimes they fail; they need to be debugged when they fail; there needs to be a fallback strategy for when they fail . . . fixing the N+1 query cut the load time down to a third, if we can find a couple of more low-hanging optimizations like that we'll be in a business. Also I'd say the slowness in the slider response indicates we could cut several seconds out in the JS alone.

**Comment by edavidsonsawyer** [comment]
@alexsoble makes sense!

**Pull request merged**
