### PR TITLE
Live Dashboard Links for Administrators

### PR DESCRIPTION
**Pull request by edavidsonsawyer**
# Who is this PR for?
Multi-school administrators. But really just Uri.

# What problem does this PR fix?
Currently accessing dashboards is done by manually typing the link

# What does this PR do?
Gives admins easy access to Dashboards via links on their homepage

# Screenshot (if adding a client-side feature)
screen shot 2018-02-02 at 3 51 53 pm

# Checklists

## Javascript QA

+ [x] Author checked latest in IE - District Admin Homepage
+ [ ] Reviewer checked latest in IE - District Admin Homepage

### CODE REVIEW

**Comment by edavidsonsawyer** [comment]
@alexsoble, when you get the chance, here's the admin side of the live links.

**Comment by alexsoble** [comment]
@edavidsonsawyer Sorry if I'm being horrifically nitpicky, but the duplication of all the school names is bugging me when I look at the screenshot.

What do you think about making the school names big and bolded and not links, and including two small links below each one?

Kinda like this:

### **ARTHUR D HEALEY**
[[overview](url)] [[dashboards](url)]

**Comment by edavidsonsawyer** [comment]
You're a cruel taskmaster, @alexsoble. 

Actually, I'm with you and was planning on doing something like that with the school admin links. Do you think we could merge this as is and I'll tidy up this page when I push the fully live version? I just want @snoopyuri to have the chance to do a sanity check on the data as soon as possible, and it's going to be a little bit later I'll have time to do anything else here.

**Comment by snoopyuri** [comment]
Just let me know….I’ve got time on Monday to do sanity checks on the data!

**Comment by edavidsonsawyer** [comment]
How about this, @alexsoble? Seems easier on the eyes.
screen shot 2018-02-04 at 11 26 03 pm

**Comment by alexsoble** [comment]
@edavidsonsawyer Beautiful! 🚢 🚢 .

**Comment by snoopyuri** [comment]
Agreed….I’ve got a good chunk of time today to test out data quality, so let me know when to start.

**Comment by alexsoble** [comment]
@edavidsonsawyer @snoopyuri This is deployed and live in production! 🙏

**Pull request merged**
