### PR TITLE
Add note to docs on using IE11 to test

### PR DESCRIPTION
**Pull request by kevinrobinson**
With links to free VMs.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@alexsoble @jhilde What do you pals think?

**Comment by alexsoble** [comment]
@kevinrobinson I think these are great resources! To be honest, I tried to use IE (via Browserstack) to test and develop earlier in the project, but I fell off the horse eventually because I use Chrome for everything else. I'm trying to think of ways to make it more difficult for us devs to develop on Chrome or at least give us big flashing warnings about it. Like maybe a big red banner on the top when you're logged in as the admin user reminding you that "this site is meant to use in IE"? This PR should definitely ship, just thinking about how to make it stick!

**Comment by kevinrobinson** [comment]
Cool, yeah I used BrowserStack a bit before too but also pretty inconsistently.  I think the VM workflow can help, since then it's just running right on your computer and basically no different than Chrome.  The developer tools are 85% as good in IE11 now too.

Warnings sound good too, https://www.npmjs.com/package/detect-browser could be a warning as well, that runs only in development or for a particular user.

**Comment by alexsoble** [comment]
👍

**Pull request merged**
