### PR TITLE
WIP - section header and section page to es6

### PR DESCRIPTION
**Pull request by Jngai**
# Who is this PR for?

Everybody that touches the code base. 

# What problem does this PR fix?

Continued on with refactoring the next section. 

# What does this PR do?

Switch sectionheader and sectionpage to es6. Remove window.shared code.
Refactored its associated test. 

# Checklists
+ [x] Author - Do a rigorous code review. 
+ [x] Author - Know where the js is getting loaded, click around in IE -  
+ [ ] Reviewer - Do a rigorous code review. 
+ [ ] Reviewer checked latest in IE -

### CODE REVIEW

**Comment by Jngai** [comment]
@alexsoble I am doing two files at the same time, refactoring like usual... There is this CI error on props that I think you can unstuck for me really quickly. Also will you confirm that these two files are mostly for styling purposes. I clicked everywhere in the app and nothing is breaking but I am not totally sure where they are getting rendered.

**Comment by alexsoble** [comment]
@Jngai The linter failure is because you have `SectionHeader.proptypes` instead of `SectionHeader.propTypes` here. The camel-case capitalization is significant.

**Comment by alexsoble** [comment]
@Jngai Is this in a good spot for review?

**Comment by Jngai** [comment]
@alexsoble I want to look at this one more time. Please review the other one first.

**Comment by Jngai** [comment]
@alexsoble I think this is in a good spot for a review.

**Comment by alexsoble** [comment]
@Jngai Hmmm, when I log in to the demo site locally in Chrome as SHS Art educator here's what I see (browser/console): 

screen shot 2017-12-08 at 10 36 27 am

**Comment by Jngai** [comment]
@alexsoble Its the same problem with `const` on the top, just brought the pic back up. 
screen shot 2017-12-13 at 11 01 17 am

**Comment by alexsoble** [comment]
FYI @Jngai closing this and moving over to #1328 like we did with the last PR.

**Pull request closed without merging**
