### PR TITLE
Add 10th Grade Experience Team event note type

### LINKED ISSUE #1061: Add 10th Grade Experience Team note type
Note: There's a 9th Grade Experience Team and a 10th Grade Experience Team but no 11th and 12 grade teams, so this is the last Experience Team type we're going to add (which is good).

### PR DESCRIPTION
**Pull request by alexsoble**
# Issue 

+ Fix #1061

### CODE REVIEW

**Comment by alexsoble** [comment]
Lots more specs to update, probably too many considering the size/scope of this change?

**Comment by jhilde** [comment]
Ughhh, at some point of course these belong in the database, not code, given their specificity to Somerville.

**Comment by alexsoble** [comment]
@jhilde Yup for sure.

**Comment by alexsoble** [comment]
@jhilde In fact, why don't I break that out into its own issue . . .

**Pull request merged**
