### PR TITLE
Unblock webpack Heroku deploys

### PR DESCRIPTION
**Pull request by alexsoble**
# Notes 

+ Unblock webpack Heroku deploys by moving webpack-required dependencies out of  `devDependencies`
+ From the Heroku/nodejs docs: "...since you usually don’t want all development dependencies in your production builds, it’s preferable to move only the dependencies you actually need for production builds (bower, grunt, gulp, etc) into dependencies." (https://devcenter.heroku.com/articles/nodejs-support)

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@alexsoble Awesome! 👍 

Would you be open to trying one other thing first, which is to tell yarn "install both sets of dependencies?"  That keeps the `package.json` accurate about which things are for development and which things are for the actual app.  I think adding `YARN_PRODUCTION=false yarn install --frozen-lockfile` before `yarn run build` in the `assets.rake` hook might do the trick.

If that doesn't work, it'd be good to also see if moving these to `devDependencies` doesn't increase the bundle size.  I don't think it will, and even if it does I think we should still ship to unblock it and tackle later, but running a building locally could quickly confirm/disconfirm.

**Comment by kevinrobinson** [comment]
@alexsoble Yeah I think in general we want NODE_ENV=production, and if we want to change the npm/yarn config to behave in a non-production way in production, we should do that in a limited specific way (eg., on the command line rather than as an environment variable in general).

The Heroku docs also apply to when you don't directly run `yarn install`, but here we do since we're a Ruby dyno and we're manually running `yarn install` in `assets.rake`.  Normally folks can't just add this in a more limited way.

**Comment by alexsoble** [comment]
@kevinrobinson OK that makes sense! I tried force-pushing the tip of the `experiment/webpack-jest` branch to the demo site, expecting the deploy to fail since webpack etc. are in `devDependencies`, but the deploy succeeded! My guess it that something must have been cached from my earlier deploys. 😅

**Comment by kevinrobinson** [comment]
Ah that is scary if deploys are not isolated and repeatable!

I can poke around at this more later this week too then, but will leave it
for last. Would rather ship to clear the large PR and revisit this after.

**Comment by kevinrobinson** [comment]
This is working now in https://github.com/studentinsights/studentinsights/pull/1182#issuecomment-339215449

**Comment by kevinrobinson** [comment]
Thanks @alexsoble!

**Pull request closed without merging**
