### PR TITLE
WIP – Add student photos to S3

### PR DESCRIPTION
**Pull request by alexsoble**
# Who is this PR for?

Initially, K8 counselors; eventually, all educators. 

# What problem does this PR fix?

Brings us closer to fixing the problem of educators who receive a large influx of new students (say, high school house masters at the start of a new school year). Educators may not recognize every student by name when looking at their Student Profile. 

# What does this PR do?

Adds rake task that imports student photos from the Somerville SFTP site to a secure Amazon S3 bucket. Next step is to add authenticated server code that checks educator authorization before sending down the image; then we can add student photos to student profiles, starting with 8th graders in time for next week's K8 Counselor/High School House Master meetings.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@alexsoble apologies if I messed this up, I thought there was a merge conflict from something else I did.  I think it's fixed up now but I'm happy to help repair any damage Monday if not!

**Comment by kevinrobinson** [comment]
Pushed a commit to resolve the merge conflict.

**Comment by alexsoble** [comment]
Ooooh, looks like this has merge conflicts right now because of changes made to the importer files upstream conflicting with my renaming files into a `csv_file_importers` directory. I think the directory name change is good, but it's not really relevant to this PR, so no harm in dropping it. 

I'm going to try to fix this by dropping the first commit from this PR (that's the one that introduced the `csv_file_importers` name change) and force-pushing.

**Comment by alexsoble** [comment]
Tried the rebase here: #1786. Doesn't look super successful to me, because the rebased version with dropped commits has a bunch of new merge conflicts, this time on unrelated files. I think this has to do with the rebase strategy not playing nicely with the manual-upstream-merge strategy used earlier in the PR. Going to explore some other options. 😄

**Comment by alexsoble** [comment]
I'm going to try another strategy . . . first, rebase from master. Then, rebase dropping the initial commits around directory renaming.

**Comment by alexsoble** [comment]
Man, that didn't work well either! I'm having a hard time rebasing this one. Right now I'm thinking it might make the most sense to just cherry-pick the commits on this branch related to the student-photo feature onto a new branch.

**Comment by alexsoble** [comment]
Alrighty, it looks like the cherry-picking strategy was really successful in #1787! The merge conflicts are gone and the commit history is much cleaner. I'm going to close this PR in favor of #1787.

**Pull request closed without merging**
