### PR TITLE
Use TestPals in development, add admin/authorization overview

### PR DESCRIPTION
**Pull request by kevinrobinson**
❗️ **This updates the local development process - see the updated README for how to login in development mode** ❗️ 

# Who is this PR for?
Developers and project admin

# What problem does this PR fix?
This updates the local development data to use `TestPals` so that the development data allows manually testing the set of educator roles that are also tested in automated tests.  These should have semantically correct relationships so that authorization rules all make sense.

It also adds an `/admin/authorization` page to audit which users have sensitive access, and to see the homeroom pages for each educator.

# What does this PR do?
It reworks `seeds.rb` to merge it into `TestPals`.

It moves the homepage code out of `ApplicationController` and into `Authorizer` for determining what kind of homepage to show, and `PathsForEducator` for computing the actual path for standalone testing.  In the process, this removes some unnecessary code and pages that were handling cases when the database had no `Section` or `Homeroom` models, and collapses that into a `no_default_page` view.

It adds `/admin/authorization`.

# Screenshot (if adding a client-side feature)
Seeding:
```

Starting seeds.rb...
Checking for existing data in the database...
Seeding database constants for Somerville...
Destroying all educators...
Creating TestPals...
Uploading services...
Creating more students for each homeroom...
  Creating for homeroom: HEA 500...
  Creating for homeroom: HEA 003...
  Creating for homeroom: WSNS 501...
  Creating for homeroom: SHS ALL...
  Creating for homeroom: SHS 917...
  Creating for homeroom: SHS 942...
Creating additional students for the Healey with no homeroom...
Creating more sophomore students...
  Creating students for section SECTION-1...
  Creating students for section SECTION-2...
  Creating students for section ART-302A...
  Creating students for section ART-302B...
  Creating students for section SCI-201A...
  Creating students for section SCI-201B...
Updating indexes...
Querying for jobs...
Found 5 jobs.
Starting precomputing...
Wrote document 1...
Wrote document 2...
Wrote document 3...
Wrote document 4...
Wrote document 5...
Done.
Done seeds.rb.
```

Authorization overview admin page (showing new development data created from `TestPals`):
screen shot 2017-12-10 at 1 53 23 pm
screen shot 2017-12-10 at 2 02 26 pm

### CODE REVIEW

**Comment by alexsoble** [comment]
Hey @kevinrobinson! This is cool, checking out the new TestPals setup on my local machine now! One question: what's the relationship between this PR and #1274? Does this supercede #1274, and if so should we close #1274?

**Comment by alexsoble** [comment]
# GIFs!

I tried out all the user roles locally and made GIFs to show visually what the experience looks like for each user.

## Uri (districtwide administrator) 

+ Logs in and sees the districtwide admin page
+ Can see all pages / data points 

test-pals-uri

## Laura (K-8 principal)

+ Logs in and sees her own school
+ Can't see a different school's data

test-pals-laura

## Vivian (K teacher) 

+ Logs in and sees her homeroom roster
+ Can't see schoolwide data

test-pals-vivian

## Hugo (HS Physics teacher)

+ Logs in and sees one of his sections
+ Can see his other section
+ Can't see a section not assigned to him

test-pals-hugo

## Sofia (9th grade counselor) 

+ Logs in and sees school overview for grade 9 only
+ Can't see Healey data

test-pals-sofia

**Comment by kevinrobinson** [comment]
@alexsoble Nice gifs!  Yeah I think these are the kinds of cases that it'd be go to go add in a specs too (in subsequent work).

re: merging, this is a single commit on to of https://github.com/studentinsights/studentinsights/pull/1274, so my suggestion in https://github.com/studentinsights/studentinsights/pull/1274#issuecomment-350574932 was to merge that PR first and then this afterward.

**Comment by alexsoble** [comment]
@kevinrobinson Oooops, sorry I missed your comment earlier, got excited by this shiny new PR! Will respond now. ✨

**Comment by alexsoble** [comment]
Hey there @kevinrobinson! Was reviewing open PRs and saw this one. These are some really fantastic changes and this looks good to merge in. How do you feel about merging it in this week? We can email devs about the new logins and talk about the changes at Friday's meeting. ✨

**Comment by kevinrobinson** [comment]
@alexsoble Thanks for reviewing!  Yeah if this seems good I think it's ready to go (I think the admin authorization in https://github.com/studentinsights/studentinsights/pull/1315/files#diff-8ae9e9a3cfdcb011c77526147f29d63fR22 is the main risk).

https://github.com/studentinsights/studentinsights/pull/1318 is the next open after this, but I broke the tests somewhere along the line and still have to fix that up too, but getting this one out would be great since everything else in on top of the changes to the `seeds.rb`.

**Comment by alexsoble** [comment]
@kevinrobinson When you say "admin authorization . . . is the main risk," do you mean admin authorization to view `app/views/admin/educators/authorization.html.erb`, or something else?

**Comment by kevinrobinson** [comment]
Yep, the controller code here: https://github.com/studentinsights/studentinsights/pull/1315/files#diff-8ae9e9a3cfdcb011c77526147f29d63fR22

**Comment by alexsoble** [comment]
@kevinrobinson Gotcha! I don't see that controller action as risky because its controller inherits `before_action :authenticate_educator!, :authenticate_admin` from Admin::ApplicationController, and it authorization logic is well-tested in `admin_educators_controller_spec.rb`.

**Comment by kevinrobinson** [comment]
@alexsoble Okay great! 👍 That's what I was going for, thanks :)

**Comment by alexsoble** [comment]
🚢

**Comment by alexsoble** [comment]
Alright, this is live in prod! The overview page at `/admin/authorization` looks great — super useful. And I did some manual Q&A to kick the tires on authorization/authentication for that page. 😄 👍

**Comment by alexsoble** [comment]
Running now:

```
./scripts/deploy/rebuild_demo.sh 
🚨  🚨  🚨  DANGER: About to destroy and rebuild the ⬢ somerville-teacher-tool-demo database.

🚨  🚨  🚨  This will cause downtime on somerville-teacher-tool-demo. Continue? [y/N] y
⚙  💻  ⚙  heroku pg:reset...
```

**Comment by alexsoble** [comment]
Rebuilding the site failed with this error message: 

```
NameError: uninitialized constant TestPals::FactoryGirl
/app/spec/support/test_pals.rb:62:in `create!'
/app/spec/support/test_pals.rb:10:in `create!'
/app/db/seeds.rb:48:in `<top (required)>'
```

I double checked — the error doesn't occur locally. So it must have something to do with what's autoloaded in production as opposed to development.

**Comment by alexsoble** [comment]
Could be this:

```
group :development, :test do
  ...
  gem 'factory_girl_rails'
  ...
end

**Comment by alexsoble** [comment]
Working on fixing the demo site building error in #1369. The real production site looks just fine and nothing is broken locally so I don't feel it's urgent to revert here.

**Pull request merged**
