### PR TITLE
Moving dashboard to ES6

### PR DESCRIPTION
**Pull request by edavidsonsawyer**
# Who is this PR for?
Developers who want to contribute to the codebase by adding or improving client-side features.

# What problem does this PR fix?
Not all our JS files use ES6 modules, which can be confusing for new JS devs coming on to the project.

# What does this PR do?
Converts all dashboard components to ES6 module

# Checklists

## Javascript QA

+ [x] Author checked latest in IE - School Administrator Dashboard links
+ [x] Author checked latest in IE - School Absences Dashboard
+ [x] Author checked latest in IE - School tardies Dashboard
+ [x] Reviewer checked latest in IE - School Administrator Dashboard links
+ [x] Reviewer checked latest in IE - School Absences Dashboard
+ [x] Reviewer checked latest in IE - School tardies Dashboard

### CODE REVIEW

**Comment by edavidsonsawyer** [comment]
@alexsoble this turned out to be pretty straightforward so I did it all in one fell swoop. Should be ready for a check when there's time.

**Comment by alexsoble** [comment]
@edavidsonsawyer Hey, awesome! Will do a quick QA on my end today. 

One small thing I noticed reviewing the changed files — some of the refactored files have a `.js` extension, and some have a `.jsx` extension. Let's move them all to `.js` for consistency since that's what we're doing in our other ES6 refactor PRs. 

I like how you're importing PropTypes as its own library to make the migration to future versions of React less work when the time comes!

**Comment by edavidsonsawyer** [comment]
@alexsoble all set! I'd been avoiding .js for anything that wasn't pure javascript.

**Comment by alexsoble** [comment]
@edavidsonsawyer Yeah, I hear what you're saying about .jsx! 

We're aiming to match `create-react-app` style with our Javascript. I did some quick searching on why `create-react-app` uses .js and found this thread about their thought process: https://github.com/facebook/create-react-app/issues/87.

I checked out this branch, `yarn start` fails because of a file name mismatch error when I try to get it started:

```
[1] ERROR in ./ui/route.js
[1] Module not found: Error: Can't resolve '../app/assets/javascripts/school_administrator_dashboard/main.jsx' in '/Users/alexsoble/studentinsights/ui'
[1]  @ ./ui/route.js 7:0-111
[1]  @ ./ui/index.js
[1]  @ multi ./ui/polyfills.js ./ui/index.js
```

One good option could be to drop the file extension entirely when `import`ing, that's what I see Kevin doing, e.g. here: https://github.com/studentinsights/studentinsights/pull/1482/files#diff-4ec7c94fc4b2658aa1b77cd800771107

**Comment by edavidsonsawyer** [comment]
@alexsoble whoops! I must have tested that last commit on the wrong branch! 

I like omitting the extensions, and had done that originally, but for some reason I got yarn errors unless I kept the extensions for sort_helpers.jsx and mixpanel_utils.jsx. I don't know why that is, so to be on the safe side I left all the extensions in. 

This new commit removes the extensions for all imports except those two above. But I'm a little concerned that I can't seem to do it across the board, so if you know why I might be running into trouble with those two I'd appreciate any light you can shed on the issue.

**Comment by alexsoble** [comment]
Hey there @edavidsonsawyer! That's weird about sort_helpers.jsx and mixpanel_utils.jsx . . . I looked at it but couldn't figure out why those two are exceptions. 

I'm not too worried about it though. Overall this PR is great and it moves the dashboard components to the same style as the rest of our JS, which is what we set out to do. I double checked that this branch compiles fine and looks good locally. Let's 🚢!

**Pull request merged**
