### PR TITLE
Edit "New Instance" documentation along with Bedford set up

### PR DESCRIPTION
**Pull request by alexsoble**
# Who is this PR for?

Developers.

# What does this PR do?

+ Update `new_instance.md` document while I set up Bedford's instance, so that the steps in the doc better match the steps of setting up a new district.
+ Remove verbose docs that weren't adding much extra value, keep a consistent checklist style.

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@alexsoble This doc lives in another place now and we could close this PR, is that right?

**Comment by alexsoble** [comment]
@kevinrobinson Yes!

**Comment by alexsoble** [comment]
@kevinrobinson To be more specific, I think this is in a good place to merge. It deletes some content, moves other content around within the doc, and moves other content to a separate checklist outside of public GitHub.

**Comment by kevinrobinson** [comment]
Ah I misunderstood - this is the overall doc I thought it was an older version of `new_sftp.md`.  Sweet, let's merge this sucker! 👍 🚢

**Comment by alexsoble** [comment]
👍

**Pull request merged**
