### PR TITLE
School overview page to es6

### PR DESCRIPTION
**Pull request by Jngai**
# Who is this PR for?
Everybody working on this code base
# What problem does this PR fix?
Continued on with next section of js refactoring.
# What does this PR do?

- Switch school_overview_page.jsx to SchoolOverViewPage.js. Rewrite it into a js module then import it everywhere it happens. Remove window.shared code.
- Refactored its associated test

# Screenshot (if adding a client-side feature)

# Checklists

## Javascript QA

*If the PR touches Javascript, follow this checklist. If the PR doesn't touch Javascript, you can delete this section.*

*Which features or pages does this PR touch? Make a list here so that you can double-check each affected page in a Internet Explorer before merging.*

/schools/hea

*Make one list for the author and another for the reviewer.*

+ [x] Author - Do a rigorous code review. 
+ [x] Author - Know where the js is getting loaded, click around in IE - School Overview 
+ [x] Reviewer - Do a rigorous code review. 
+ [x] Reviewer checked latest in IE - School Overview

### CODE REVIEW

**Comment by Jngai** [comment]
@alexsoble I fixed two bugs and clicked everywhere. I search for `window.shared.SchoolOverviewPage` and removed all of them. Spec work has already been done in #1224 for this. I think its your turn to review.

**Comment by alexsoble** [comment]
@Jngai I manually testing setting/unsetting filters, using the ESC key to clear filters, clicking student links, and sorting table columns in an Internet Explorer VM, all looked good! 

I also looked through the code. All of the bugs we've come across have involved mistakes with `this`, often around making sure context is bound before we pass functions to components. I checked both the functions that get passed to other components as props, they're both properly bound here.

Time to 🚢  this!

**Comment by Jngai** [comment]
@alexsoble Great! on to the next one.

**Comment by alexsoble** [comment]
@Jngai Yup! I deployed and checked in production on Internet Explorer, looks good.

**Pull request merged**
