### PR TITLE
Add date to tardies tooltip

### PR DESCRIPTION
**Pull request by edavidsonsawyer**
# Who is this PR for?
School Administrators using the tardies dashboard

# What problem does this PR fix?
From user testing, it's apparent that users will want to know the day of the week for each data point in the schoolwide tardies. 

# What does this PR do?
Adds the date, including day of the week, to the tooltip.

# Screenshot (if adding a client-side feature)

tardies_tooltip

# Checklists

## Javascript QA

+ [x] Author checked latest in IE - Tardies Dashboard
+ [ ] Reviewer checked latest in IE - Tardies Dashboard

### CODE REVIEW

**Comment by edavidsonsawyer** [comment]
Hey, @alexsoble, this is just a quick add from user feedback. I'd like to get this in before the link goes live.

**Comment by alexsoble** [comment]
Hey @edavidsonsawyer! I reviewed this PR with the demo data environment, and it left me with a question:

tardy-tooltip

What are the units for the X-Axis on this chart? Are they weeks, or something else? I couldn't figure out why hovering on each bar would give me seemingly nondeterministic days of the week like Sat, Sat, Weds, Thurs instead of a more predictable pattern.

**Comment by edavidsonsawyer** [comment]
Interesting point, @alexsobel. Each of those bars represents a school day. But the school days are calculated based on overall School attendance. Because demo attendance is randomized and doesn't connect to any particular school day, you won't see an obvious pattern like Monday Tuesday etc. With the production data, or richer demo data, this is a lot more intuitive. We could also add another label to the x-axis to explain each bar is a school day, but with the months already indicated I'm not sure that's necessary provided the attendance data looks like it would in the school.

**Comment by alexsoble** [comment]
@edavidsonsawyer Here's what the X-Axis looks like in production for the Healey school (cutting off the tops of the bars here):

screen shot 2018-01-29 at 1 34 25 pm

October and November are really squished together. My intuition looking at the graphs was that months would be more or less even. Do you think it would make it simpler for users to include all days in the X-axis? Non-school days like weekends would presumably have zero events in them, so no bar, but that doesn't seem unreasonable to me.

**Comment by edavidsonsawyer** [comment]
@alexsoble, I tried it out with all dates and it looks fine locally. I'd appreciate it if you could check in production just to make certain it's still well-behaved. 

I also removed the first month from the x axis categories to prevent that overlap, since that label isn't really necessary, and is somewhat misleading as is. Glad you noticed that!

**Comment by alexsoble** [comment]
@edavidsonsawyer Will do! And I'll send you screenshots! 📸

**Comment by alexsoble** [comment]
@edavidsonsawyer Here's a screenshot from IE with this branch:

screen shot 2018-01-30 at 5 56 57 pm

The X-axis looks much cleaner and when I look at it I can see intuitively that each bar represents one day in the month.

One thing I noticed was that all of the bars are weekdays, and weekends are skipped. Is that a feature or a bug? I could see it either way, but if we show an empty space on the X-Axis for weekends then users will be immediately able to see the shape of the week, which should make the X-Axis units even crisper and more obvious.

**Comment by edavidsonsawyer** [comment]
@alexsoble, that's strange. It _should_ be showing empty spaces on the weekends. Locally I reset my db so the data isn't a good model, but you can see big gaps corresponding to dates that are missing tardies.
screen shot 2018-01-30 at 9 46 28 pm

This is a little tricky to debug without being able to run this against the live site. Do you think you could log the seriesData variable to the console in school_tardies_dashboard.jsx and send it to me? It's just an array matching dates to numbers of tardies, so no problematic info but it might let me see what's happening there.

**Comment by alexsoble** [comment]
@edavidsonsawyer Yep, will get you that this afternoon!

**Comment by alexsoble** [comment]
@edavidsonsawyer Here you go! I do see the weekends in the seriesData, and I see them in the chart now too! 

Maybe I didn't have your latest commits the last time I reviewed? Apologies for that. The chart shows weeks, weekends and school breaks very clearly, I'll attach a screenshot below. 

I think this PR looks great to go if you do! 

```
[
  [
    "Tue 10/31",
    0
  ],
  [
    "Wed 11/01",
    0
  ],
  [
    "Thu 11/02",
    0
  ],
  [
    "Fri 11/03",
    10
  ],
  [
    "Sat 11/04",
    0
  ],
  [
    "Sun 11/05",
    0
  ],
  [
    "Mon 11/06",
    19
  ],
  [
    "Tue 11/07",
    0
  ],
  [
    "Wed 11/08",
    24
  ],
  [
    "Thu 11/09",
    25
  ],
  [
    "Fri 11/10",
    0
  ],
  [
    "Sat 11/11",
    0
  ],
  [
    "Sun 11/12",
    0
  ],
  [
    "Mon 11/13",
    26
  ],
  [
    "Tue 11/14",
    23
  ],
  [
    "Wed 11/15",
    21
  ],
  [
    "Thu 11/16",
    56
  ],
  [
    "Fri 11/17",
    21
  ],
  [
    "Sat 11/18",
    0
  ],
  [
    "Sun 11/19",
    0
  ],
  [
    "Mon 11/20",
    27
  ],
  [
    "Tue 11/21",
    30
  ],
  [
    "Wed 11/22",
    22
  ],
  [
    "Thu 11/23",
    0
  ],
  [
    "Fri 11/24",
    0
  ],
  [
    "Sat 11/25",
    0
  ],
  [
    "Sun 11/26",
    0
  ],
  [
    "Mon 11/27",
    30
  ],
  [
    "Tue 11/28",
    27
  ],
  [
    "Wed 11/29",
    21
  ],
  [
    "Thu 11/30",
    22
  ],
  [
    "Fri 12/01",
    34
  ],
  [
    "Sat 12/02",
    0
  ],
  [
    "Sun 12/03",
    0
  ],
  [
    "Mon 12/04",
    26
  ],
  [
    "Tue 12/05",
    33
  ],
  [
    "Wed 12/06",
    24
  ],
  [
    "Thu 12/07",
    25
  ],
  [
    "Fri 12/08",
    22
  ],
  [
    "Sat 12/09",
    0
  ],
  [
    "Sun 12/10",
    0
  ],
  [
    "Mon 12/11",
    34
  ],
  [
    "Tue 12/12",
    24
  ],
  [
    "Wed 12/13",
    31
  ],
  [
    "Thu 12/14",
    17
  ],
  [
    "Fri 12/15",
    36
  ],
  [
    "Sat 12/16",
    0
  ],
  [
    "Sun 12/17",
    0
  ],
  [
    "Mon 12/18",
    42
  ],
  [
    "Tue 12/19",
    35
  ],
  [
    "Wed 12/20",
    30
  ],
  [
    "Thu 12/21",
    24
  ],
  [
    "Fri 12/22",
    34
  ],
  [
    "Sat 12/23",
    0
  ],
  [
    "Sun 12/24",
    0
  ],
  [
    "Mon 12/25",
    0
  ],
  [
    "Tue 12/26",
    0
  ],
  [
    "Wed 12/27",
    0
  ],
  [
    "Thu 12/28",
    0
  ],
  [
    "Fri 12/29",
    0
  ],
  [
    "Sat 12/30",
    0
  ],
  [
    "Sun 12/31",
    0
  ],
  [
    "Mon 01/01",
    0
  ],
  [
    "Tue 01/02",
    26
  ],
  [
    "Wed 01/03",
    37
  ],
  [
    "Thu 01/04",
    0
  ],
  [
    "Fri 01/05",
    0
  ],
  [
    "Sat 01/06",
    0
  ],
  [
    "Sun 01/07",
    0
  ],
  [
    "Mon 01/08",
    46
  ],
  [
    "Tue 01/09",
    41
  ],
  [
    "Wed 01/10",
    36
  ],
  [
    "Thu 01/11",
    33
  ],
  [
    "Fri 01/12",
    13
  ],
  [
    "Sat 01/13",
    0
  ],
  [
    "Sun 01/14",
    0
  ],
  [
    "Mon 01/15",
    0
  ],
  [
    "Tue 01/16",
    36
  ],
  [
    "Wed 01/17",
    12
  ],
  [
    "Thu 01/18",
    34
  ],
  [
    "Fri 01/19",
    39
  ],
  [
    "Sat 01/20",
    0
  ],
  [
    "Sun 01/21",
    0
  ],
  [
    "Mon 01/22",
    32
  ],
  [
    "Tue 01/23",
    29
  ],
  [
    "Wed 01/24",
    28
  ],
  [
    "Thu 01/25",
    24
  ],
  [
    "Fri 01/26",
    26
  ],
  [
    "Sat 01/27",
    0
  ],
  [
    "Sun 01/28",
    0
  ],
  [
    "Mon 01/29",
    38
  ],
  [
    "Tue 01/30",
    0
  ]
]
```

# Screenshot

screen shot 2018-01-31 at 1 12 57 pm

**Comment by edavidsonsawyer** [comment]
@alexsoble, this is great. I think they'll get a lot of use from seeing the weekly patterns, nice call! Let's merge it!

**Comment by alexsoble** [comment]
@edavidsonsawyer 👍 ✨ 👍 🚢

**Comment by alexsoble** [comment]
@edavidsonsawyer Deployed!

**Pull request merged**
