### PR TITLE
Adding Percentile to the end of STAR Assessments for clarity

### PR DESCRIPTION
**Pull request by jhilde**
Uri had requested this quick UI change to make it clear that STAR assessments are using percentile. 

@kevinrobinson @alexsoble Uri is demoing this to assistant principals tomorrow, would be great to ship tonight. ;-)

### CODE REVIEW

**Comment by alexsoble** [comment]
OK. I'm restarting the test build since the last build appears to have failed non-deterministically.

**Comment by jhilde** [comment]
Merci

**Comment by kevinrobinson** [comment]
@jhilde coming atcha!

**Comment by kevinrobinson** [comment]
@alexsoble Maybe we should take a look at the build, seems like it has been flaky this week.

**Pull request merged**
