### PR TITLE
Add to Sublime project settings

### PR DESCRIPTION
**Pull request by alexsoble**
## Notes

+ Add whitespace, tabs, and eof rules to `.sublime-project` file
+ Use our Sublime project settings by default	when new user clones the repo

### CODE REVIEW

**Comment by alexsoble** [comment]
Look good @erose?

**Comment by erose** [comment]
Good to formalize this stuff. I'll add "use Open Project in Sublime to open our sublime-project file" to the docs.

**Comment by alexsoble** [comment]
@erose Oooooh, so devs will need to go Project > Open Project > `studentinsights.sublime-project` every time they want to work on the project? There's no shortcut?

**Comment by erose** [comment]
Nope -- you only need to do it once. Sublime persists your last opened project, which files it had open, where the cursor was, etc. in the `*.sublime-workspace` file. (Which is why that's in the `.gitingore` now).

Ref: http://www.joshuawinn.com/understanding-projects-in-sublime-text-saving-switching-etc/

I added some clarification to the docs. (I had no idea how this worked before looking into this just now).

**Comment by alexsoble** [comment]
Oh, neat! Yeah, I'm learning all of this for the first time too. 

I'll undo https://github.com/studentinsights/studentinsights/pull/471/commits/f1b534c22b5a406b56c5ee097c33e0820aaea6a4. Misunderstood how this works!

**Comment by erose** [comment]
Merging so new people tonight can take advantage of it.

**Comment by alexsoble** [comment]
@erose Great!

**Pull request merged**
