### PR TITLE
Unify Transition Note endpoints

### PR DESCRIPTION
**Pull request by alexsoble**
# Who is this PR for?

K-8 Counselors. 

# What problem does this PR fix?

Closes a bug in a note-saving edge case, when multiple requests are fired off to the server quickly.

# What does this PR do?

+ Changes the controller code for Transition Notes to only implement one action, `#update`. This removes the possibility of bugs around create/update confusion.
+ Fixes the validation logic on Transition Note to say that there can only be one regular and one restricted note. 
+ Adds unit tests for the model, controller tests for the controller, and smoke test for the JS component. 
+ Disables firing off more than one request per "thread" (restricted/non-restricted note) at a time.

# GIF

unify

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@alexsoble I pushed https://github.com/studentinsights/studentinsights/pull/1764/commits/40d56a039ee8b22e40f82a503a0a02d1ae630846 to fixup the JS test failures https://travis-ci.org/studentinsights/studentinsights/builds/388541140?utm_source=github_status&utm_medium=notification from our last set of changes.

**Comment by alexsoble** [comment]
Cherry-picked e2d19518bf787c4930e3205510f57f75a6cf30fa on top. Next I'm going to force-push to the demo site to QA before merging.

**Comment by alexsoble** [comment]
Ah. Failing snapshot test due to removing the line breaks from the transition note prompts. Darn. I looked here (https://facebook.github.io/jest/docs/en/snapshot-testing.html) for info about updating snapshot tests. Looks like we don't have `jest --updateSnapshot` or `yarn test "Press (u) to update failing snapshots"` available to us right now.

**Comment by alexsoble** [comment]
When I QA this on the demo site, I'm seeing strange behavior where the restricted note button gets stuck on a "Saving..." state. So I don't think this is in a good place to merge right now.

**Comment by kevinrobinson** [comment]
Pushed a commit to resolve the merge conflicts from https://github.com/studentinsights/studentinsights/pull/1739, which impacted `PageContainer` and `StudentProfilePage` in minor ways.

**Comment by alexsoble** [comment]
@kevinrobinson I deployed, manually QA'ed in the Heroku demo site, and reviewed the "Files Changed" for this PR one more time. 

I couldn't recreate any error scenarios in my QA'ing. A bit frustrating that I can't reproduce whatever this was: https://github.com/studentinsights/studentinsights/pull/1764#issuecomment-395267476, but then again when I wrote that comment I was testing in the middle of a super busy week where we were flipping between deep brainstorming and bug fixing. 

Would you mind giving this branch a thorough QA to see if you can find any bugs? And then if nothing comes up, let's ship. I'll review #1785 at the same time. 😎

**Comment by kevinrobinson** [comment]
@alexsoble confirmed that I can reproduce a bug related to "saving.." locally, looking at that now to get you better info.

**Comment by alexsoble** [comment]
QA'ed the latest commit locally and on the demo site. I think we're good to 🚢!

**Comment by alexsoble** [comment]
Deploying now 🚀

**Pull request merged**
