### PR TITLE
Bug Fix: double counting each student's first absence

### PR DESCRIPTION
**Pull request by edavidsonsawyer**
# Who is this PR for?
Dashboard Users
# What problem does this PR fix?
The first absence for each student is being counted twice. This is only a problem in the absence dashboard. Tardies shouldn't have this issue. 

# What does this PR do?
Counts each absence once!

# Checklists

## Javascript QA

+ [x] Author checked latest in IE - Absence Dashboard
+ [ ] Reviewer checked latest in IE - Absence Dashboard

### CODE REVIEW

**Comment by edavidsonsawyer** [comment]
@alexsoble, when you get the chance, this should fix the bug @snoopyuri saw this morning.

**Comment by alexsoble** [comment]
@edavidsonsawyer Can we add/expand spec coverage for this function? Since this is really important code, let's make sure our specs cover it really thoroughly.

**Comment by edavidsonsawyer** [comment]
@alexsoble we definitely do want to spec coverage for this and the other calculation functions for the dashboard. There are quite a few of them, but I had wanted to wait to confirm that there was nothing wrong with the overall approach (something like the dashboard totals not looking anything like the Aspen data).  

Later tonight I'll be able to push a more comprehensive spec for all the things the dashboard is doing here. But we should move this fix in so we don't have broken code in production, I'm so we have a chance to surface any other issues.

**Comment by alexsoble** [comment]
@edavidsonsawyer Works for me, I'll merge this and make a new issue about expanding spec coverage.

**Comment by alexsoble** [comment]
@edavidsonsawyer Deployed!

**Pull request merged**
