### PR TITLE
Start harmonizing homeroom table against unified table design

### PR DESCRIPTION
**Pull request by alexsoble**
# What's new? 

+ Removed old CSS that was hyper-specific to the homeroom roster page and out of sync with the rest of the project
+ Moved the homeroom roster page closer to the styles set out in #553

# Issue 

+ #553

### CODE REVIEW

**Comment by jhilde** [comment]
FYI, I've been working on very similar work for sections. Essentially, I'm making the roster configurable for reuse.

**Comment by alexsoble** [comment]
Ok -- is there anything I need to know about your work as I work on this
PR?

Is your work on a separate branch that doesn't have a PR yet?

**Comment by jhilde** [comment]
@alexsoble (and @kevinrobinson) Take a look at [app/assets/javascripts/components/roster.jsx](https://github.com/jhilde/studentinsights/blob/hs/section_view/app/assets/javascripts/components/roster.jsx)

Basically, I'm creating a pure UI react component that can render rosters like we have in school, homeroom, and section views. It knows nothing of the underlying data so it can be reused for each of those with configuration.

You can see where I use it [app/assets/javascripts/section/section_page.jsx](https://github.com/jhilde/studentinsights/blob/hs/section_view/app/assets/javascripts/section/section_page.jsx): 

Currently working on adding super headers and will be adding the same sort ordering functions we have in homeroom and school (i.e. mostly enum sorting). Essentially, I'm adding features to the roster that are required for section view but can be reused for other views of roster-y data.

The code is largely based on [app/assets/javascripts/components/students_table.jsx](https://github.com/jhilde/studentinsights/blob/hs/section_view/app/assets/javascripts/components/students_table.jsx) 

My ideas around configuration via props is based on: [react-json-table](https://github.com/arqex/react-json-table)

**Comment by alexsoble** [comment]
@jhilde Hey Justin! This looks like really cool work but I'd suggest more communication around it. If there's no PR or discussion about it in the Issues then the other coders on the project won't know you're working on this and we could end up duplicating efforts.

**Comment by alexsoble** [comment]
@jhilde and I talked about this over the phone. I'm going to finish up this PR, which mostly focuses on the CSS / front end but doesn't extract out any JSX components yet. Then @jhilde will pull the  changes into his repo and continue the awesome work on extracting a more universal component for tables within the app! 👍

**Comment by kevinrobinson** [comment]
@jhilde @alexsoble 🌮 👍 🌮  this looks great, and thanks for the cc @jhilde this is great to know about too!

**Comment by alexsoble** [comment]
Screenshot of changes so far: 

screen shot 2017-08-26 at 3 48 22 pm

+ Stripped out whitespace to make table fullscreen like school overview page 
+ Added alternating row colors as described in the issue
+ Toned down table padding to move closer to school overview page

**Pull request merged**
