### PR TITLE
My notes page 1405

### PR DESCRIPTION
**Pull request by gabivoicu**
# Who is this PR for?
Educators

# What problem does this PR fix?
Improve Notes Feed feature based on feedback

# What does this PR do?
- Change notes feed page from loading notes by days to loading notes by count
- Only display load more button if there are more notes to show

# Screenshot (if adding a client-side feature)

# Checklists

## Javascript QA

+ [x] Author checked latest in IE - Notes Feed
+ [x] Author checked latest in IE - Student Dashboard - Interventions - Notes List: display & functionality
+ [x] Reviewer checked latest in IE - Notes Feed
+ [x] Reviewer checked latest in IE - Student Dashboard - Interventions - Notes List: display & functionality

### CODE REVIEW

**Comment by gabivoicu** [comment]
Hey @alexsoble, opened up this PR with the first change, 30 days to 30 notes. A couple of things:

- I found a bug 🚨 On line 15 of `javascripts/notes_feed/PageContainer.js`, that multiplier needs to start at 2, not 1. I believe that is affecting production right now, and what is happening is that a teacher will need to click that button twice to get notes from the past 60 days. Do you want me to make a separate PR with just that or how else should we proceed?

- I'm thinking we should update the text at the top, but I am not sure to what? 🤔 `Notes you created in the past 30 days.` does not accurately reflect what is on the page (and it didn't even before, once a teacher clicked the button the first time). We could change it to `Notes you have created.`, but that feels kind of short. Do you have any suggestions?

**Comment by gabivoicu** [comment]
That sounds good to me @alexsoble, I'll make that change to the text + finish work on the button tomorrow!

**Comment by gabivoicu** [comment]
@alexsoble This is ready for review. I'll have a bit of time tonight to address any feedback (and fix that test).

**Comment by alexsoble** [comment]
Heya @gabivoicu! I pulled this down and tested it out with a user who had lots of generated event notes. The feature worked and looked great! 

I think the spec and the merge conflicts are the only issues I can see, once those are fixed let's 🚢!

**Comment by alexsoble** [comment]
👍 👍 🚢 🚢

**Comment by alexsoble** [comment]
@gabivoicu Shipped, this is live in prod now!

**Pull request merged**
