### PR TITLE
Add pinger script

### PR DESCRIPTION
**Pull request by kevinrobinson**
This is on top of https://github.com/studentinsights/studentinsights/pull/637, which should be merged first.

This uses [CasperJS](http://casperjs.org/), a wrapper of utilities around PhantomJS to sign in and request various pages from Student Insights.  The idea is we could run this every 5min or so to get more data about response time variability related to: https://github.com/studentinsights/studentinsights/issues/627

@alexsoble @erose I'm not sure this is the best idea, but seems like it might help.  Any ideas or thoughts?

### CODE REVIEW

**Comment by alexsoble** [comment]
So just to re-phrase in my own words . . . This is a tool that will hit the production app with real requests so that we get a regular, consistent stream of data about page load times.

That sounds really useful, my reaction is 👍 .

**Comment by kevinrobinson** [comment]
@alexsoble Yep, the downside is it makes the server do more work, and maybe drowns out other real activity in the logs.  But I'm not sure how else to investigate what looked like really large variance in response times so it seems like it could give a useful data point.

**Comment by alexsoble** [comment]
@kevinrobinson We could set it to run once per day instead of every 5 minutes to reduce the server-work and the log-drowning.

**Comment by alexsoble** [comment]
@kevinrobinson Also, any reason not to merge this?

**Comment by kevinrobinson** [comment]
@alexsoble Yep, once a day would reduce the load but won't generate more useful data points about performance variability.  I think we'd need to run it regularly for it to be useful for that purpose, but hopefully the site can take a few requests every five minutes just fine :)

I'll merge, but this isn't running anywhere yet.

**Pull request merged**
