### PR TITLE
Double quotes for deploy script

### PR DESCRIPTION
**Pull request by kevinrobinson**
# Who is this PR for?
developers, follow on to https://github.com/studentinsights/studentinsights/pull/1903

# What problem does this PR fix?
deploy script argument escaping

# What does this PR do?
double quote the args

```
$ yarn --version
1.3.2

$ sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

@alexsoble maybe this will help?

### CODE REVIEW

**Comment by alexsoble** [comment]
@kevinrobinson Works but the colors are off, and there are stray quotes in `['demo]` and `[new bedford']`:

```
🚢  Fetching from GitHub...
🚢  Deploying...
yarn run v1.2.1
$ /Users/alexsoble/studentinsights/node_modules/.bin/concurrently --names \''demo,somerville,new-bedford'\' -c \''yellow.bold,blue.bold,magenta.bold'\' \''scripts/deploy/deploy.sh demo'\' \''scripts/deploy/deploy.sh somerville'\' \''scripts/deploy/deploy.sh new-bedford'\'
['demo] 🚢  🚢  🚢  Deploying code to demo.
[somerville] 🚢  🚢  🚢  Deploying code to somerville.
[new-bedford'] 🚢  🚢  🚢  Deploying code to new-bedford.
[new-bedford'] remote: Compressing source files...remote: Compressing source files...remote: Compressing source files... done.
[somerville] remote: Building source:
['demo]  done.
['demo] remote: Building source:
[new-bedford']  done.
[new-bedford'] remote: Building source:
[new-bedford'] remote:
[new-bedford'] remote: -----> Node.js app detected
['demo] remote: remote:
[new-bedford'] remote: -----> Creating runtime environment
[new-bedford'] remote:
[new-bedford'] remote:        NPM_CONFIG_LOGLEVEL=error
[new-bedford'] remote:        NODE_VERBOSE=false
[new-bedford'] remote:        NODE_ENV=production
[new-bedford'] remote:        NODE_MODULES_CACHE=true
[new-bedford'] remote:
remote: -----> Installing binaries
[new-bedford'] remote:        engines.node (package.json):  ^8.11.1
[new-bedford'] remote:        engines.npm (package.json):   unspecified (use default)
[new-bedford'] remote:        engines.yarn (package.json):  unspecified (use default)
[new-bedford'] remote:
[new-bedford'] remote:        Resolving node version ^8.11.1...
[new-bedford'] remote:        Downloading and installing node 8.11.3...
[somerville] remote:
```

**Comment by kevinrobinson** [comment]
@alexsoble got it, can you share the version info about `/bin/sh` and `yarn` like above?  I think you are running yarn `v1.2.1` based on the output you shared and upgrading will resolve this, but the version check can confirm that.

**Comment by alexsoble** [comment]
@kevinrobinson You were right, it was a yarn version issue! After mucking around and discovering that I had installed yarn multiple ways (npm, brew, etc), I figured it out and upgraded. Now:

```
» yarn -v
1.9.2
```

Added a slight tweak with f75f208360c0909e0d639a077bf096802170890c. Looks like the single-within-double-quotes is only needed when there's whitespace within an argument (`"'scripts/deploy/deploy.sh demo'"`) but not when an argument is a single string without spaces (`"yellow.bold,blue.bold,magenta.bold"`).

**Comment by alexsoble** [comment]
selfie

**Pull request merged**
