### PR TITLE
Add a red button for accessing the sped referral packets from the stu…

### PR DESCRIPTION
**Pull request by eudaimonious**
…dent profile. Issue #502 

sped_button

### CODE REVIEW

**Comment by erose** [comment]
Yo, this is pretty cool! Didn't know this was so far along.

**Comment by erose** [comment]
One thing I'm thinking: should this be on the top of the page? Is it logically tied to the "Interventions" tab?

**Comment by eudaimonious** [comment]
@erose I had no idea where to put it. Is the "Interventions" tab where it is now or is that something else? My thinking at the time was that it'll only be used a few times a year or something I didn't think it deserved the priority of being up top.

**Comment by eudaimonious** [comment]
@erose and I talked and decided to move the button to here:

full_case_history

**Comment by iamctodd** [comment]
I'll tackle this after I get the style guide in place.

**Comment by erose** [comment]
@iamctodd: I think they're on that, but thanks!

**Comment by alexsoble** [comment]
This looks good @eudaimonious @erose! I would add a line in the packet itself about beta / experimental status. The "Somerville Public Schools - SPED referral packet" title sounds official.

**Pull request merged**
